Repository Hanium2023-WeB/starD-frontend, pull requests merged in 2024-12, with the labels that each got.

#78 feat 스터디 모집
  .idea/dataSources.xml
  src/components/repeat_etc/Header.js
  src/components/study/StudyInfo.js
  src/components/study/StudyListItem.js
  src/components/study/Tag.js
  src/css/study_css/MyOpenStudy.css
  src/css/study_css/StudyOpenForm.css
  src/pages/studypage/Study.js
  src/pages/studypage/StudyDetail.js
  src/pages/studypage/StudyEdit.js
  src/pages/studypage/StudyInsert.js
  src/util/RegionSelectBox.js
Labels: ♻️ refactor, ✨ feature

#80 feat 스터디 검색
  src/App.css
  src/App.js
  src/SearchBar.js
  src/css/study_css/SearchBar.css
  src/pages/Home.js
  src/pages/studypage/SearchResult.js
  src/pages/studypage/Study.js
Labels: ♻️ refactor, ✨ feature

#82 feat 스터디 참여 신청
  src/pages/studypage/StudyApplyForm.js
  src/pages/studypage/StudyApplyList.js
  src/pages/studypage/StudyDetail.js
Labels: ♻️ refactor, ✨ feature

#84 feat 스터디 신청자 선택
  src/css/study_css/ApplyList.css
  src/pages/studypage/StudyApplyList.js
Labels: ♻️ refactor, ✨ feature

#87 feat 스터디 스크랩
  src/components/study/StudyListItem.js
  src/pages/studypage/Study.js
Labels: ♻️ refactor, ✨ feature

#91 feat 스터디 댓글
  src/components/comment/Comment.js
  src/components/comment/CommentEdit.js
  src/components/comment/CommentList.js
  src/css/comment_css/Comment.css
  src/pages/TeamCommunity/StudyPostDetail.js
  src/pages/community/PostDetail.js
  src/pages/qna/FaqDetail.js
  src/pages/qna/QnaDetail.js
  src/pages/studypage/StudyDetail.js
  src/setupProxy.js
Labels: ♻️ refactor, ✨ feature

#93 feat 기타 수정
  src/SearchBar.js
  src/components/qna/QnaListItem.js
  src/components/study/StudyListItem.js
  src/pages/qna/QnaDetail.js
  src/pages/studypage/Study.js
Labels: ♻️ refactor, ✨ feature

#95 feat 마이페이지 스크랩 스터디 리스트 조회
  src/components/study/StudyListItem.js
  src/pages/mypage/MyScrapStudy.js
  src/pages/studypage/Study.js
  src/util/scrapHandler.js
Labels: ♻️ refactor, ✨ feature

#97 feat qna 검색
  src/SearchBar.js
  src/css/study_css/SearchBar.css
  src/css/study_css/StudyDetail.css
  src/pages/qna/Qna.js
  src/pages/qna/QnaDetail.js
Labels: ♻️ refactor, ✨ feature

#99 feat 커뮤니티
  src/components/community/PostEdit.js
  src/components/community/PostInsert.js
  src/components/community/PostListItem.js
  src/css/community_css/Community.css
  src/pages/community/Community.js
  src/pages/community/PostDetail.js
  src/pages/qna/QnaDetail.js
  src/pages/qna/QnaInsert.js
  src/pages/studypage/StudyEdit.js
Labels: ♻️ refactor, ✨ feature

#103 fix: 커뮤니티 게시글 수정 시 url 쿼리 파라미터가 붙는 문제 해결
  src/components/community/PostEdit.js
  src/pages/community/PostDetail.js
  src/pages/qna/QnaDetail.js
Labels: :bug: fix

#101 feat 커뮤니티 게시글 검색
  src/App.js
  src/components/community/CommSearchBar.js
  src/components/community/PostInsert.js
  src/pages/community/Community.js
  src/pages/studypage/Study.js
Labels: ♻️ refactor, ✨ feature

#104 feat 스터디 스크랩, 게시글 좋아요
  src/components/community/PostListItem.js
  src/components/repeat_etc/Category.js
  src/css/study_css/MyOpenStudy.css
  src/css/study_css/MyParticipateStudy.css
  src/pages/community/Community.js
  src/pages/community/PostDetail.js
  src/pages/mypage/MyScrapCommunityPost.js
  src/pages/mypage/MyScrapStudy.js
  src/pages/mypage/MyWritePost.js
  src/util/likeHandler.js
Labels: ♻️ refactor, ✨ feature

#106 feat 로그아웃
  src/components/repeat_etc/Header.js
  src/pages/userpage/Logout.js
Labels: ♻️ refactor, ✨ feature

#108 feat FAQ
  src/App.js
  src/pages/admin/FaqInsert.js
  src/pages/qna/QnaDetail.js
  src/pages/qna/QnaInsert.js
Labels: ♻️ refactor, ✨ feature

#114 feat 공지사항
  .github/pull-request-template
  src/components/notice/NoticeEdit.js
  src/components/notice/NoticeListItem.js
  src/components/notice/NoticeSearchBar.js
  src/pages/notice/Notice.js
  src/pages/notice/NoticeDetail.js
  src/pages/notice/NoticeInsert.js
  src/pages/notice/NoticeSearchResult.js
Labels: ✨ feature

#117 feat 주간 인기 태그 Top 5 조회
  src/pages/Home.js
  src/pages/studypage/Study.js
  src/setupProxy.js
Labels: ♻️ refactor, ✨ feature

#118 feat 팀블로그 홈 화면
  src/pages/studypage/TeamBlog.js
Labels: ♻️ refactor, ✨ feature

#123 feat 신청, 개설, 참여한 스터디
  src/components/community/PostInsert.js
  src/components/study/StudyListItem.js
  src/components/teamcommunity/TeamPostInsert.js
  src/components/teamcommunity/TeamPostListItem.js
  src/css/study_css/MyOpenStudy.css
  src/pages/TeamCommunity/TeamCommunity.js
  src/pages/mypage/MyApplyStudy.js
  src/pages/mypage/MyOpenStudy.js
  src/pages/mypage/MyParticipateStudy.js
Labels: ♻️ refactor, ✨ feature

#124 feat 팀블로그 스터디 게시글
  src/App.js
  src/components/comment/Comment.js
  src/components/repeat_etc/TeamBlogGnb.js
  src/components/study/StudyListItem.js
  src/components/teamcommunity/TeamPostListItem.js
  src/css/community_css/Community.css
  src/pages/Home.js
  src/pages/TeamCommunity/StudyPostDetail.js
  src/pages/TeamCommunity/TeamCommunity.js
  src/pages/studypage/Study.js
  src/util/likeHandler.js
  src/util/scrapHandler.js
Labels: ♻️ refactor, ✨ feature

#125 feat 채팅
  src/components/chat/Chat.js
  src/pages/studypage/StudyApplyList.js
  src/setupProxy.js
Labels: ♻️ refactor, ✨ feature

#128 refactor 스터디 팀블로그 gnb 수정
  src/App.js
  src/components/datacontext/TeamBlogContext.js
  src/components/repeat_etc/Category.js
  src/components/repeat_etc/TeamBlogGnb.js
  src/pages/TeamCommunity/StudyPostDetail.js
  src/pages/TeamCommunity/TeamCommunity.js
  src/pages/TeamMember/TeamMember.js
  src/pages/TeamToDo/TeamToDoList.js
  src/pages/mypage/MyParticipateStudy.js
  src/pages/mypage/Mypage.js
  src/pages/studypage/TeamBlog.js
Labels: ♻️ refactor

#130 fix 로그인 안했을시 로그인 페이지로만 이동하는 오류 수정
  src/components/repeat_etc/Header.js
Labels: :bug: fix

#127 refactor: 자잘한 코드 수정
  src/App.js
  src/css/user_css/Find.css
  src/pages/Home.js
  src/pages/studypage/Study.js
  src/pages/studypage/StudyDetail.js
  src/pages/userpage/FindPW.js
  src/pages/userpage/Login.js
  src/pages/userpage/ResetPwEmailSent.js
  src/pages/userpage/ResetPwTokenVerification.js
Labels: :bug: fix, ♻️ refactor
