Repository Hanium2023-WeB/starD-frontend, pull requests merged in 2025-02, with the labels that each got.

#180 fix: 신고 관리자 페이지 에러 수정 / 스터디 중단 API 연동
  src/components/study/StudyInfo.js
  src/pages/TeamMember/TeamMember.js
  src/pages/admin/ReportManagement.js
Labels: bug, :bug: fix

#181 feat 팀원평가
  src/App.js
  src/components/evaluate/MemberEvaluateInsert.js
  src/components/repeat_etc/Backarrow.js
  src/components/study/HomeDashBoard.js
  src/components/study/StudyListItem.js
  src/css/mypage_css/edit.css
  src/css/study_css/MyOpenStudy.css
  src/css/study_css/MyParticipateStudy.css
  src/css/study_css/StudyDetail.css
  src/css/study_css/StudyOpenForm.css
  src/pages/Home.js
  src/pages/mypage/EditProfile.js
  src/pages/mypage/Editinfo.js
  src/pages/mypage/MemberEvaluate.js
  src/pages/mypage/MyEvaluation.js
  src/pages/mypage/MyPage.js
  src/pages/mypage/MyParticipateStudy.js
  src/pages/mypage/MyScore.js
  src/pages/mypage/MyWritePost.js
  src/pages/mypage/Profile.js
  src/pages/qna/Qna.js
  src/pages/studypage/Study.js
Labels: ♻️ refactor, ✨ feature

#183 fix: SyntaxError 해결
  src/components/study/HomeDashBoard.js
Labels: :bug: fix
