Repository Hanium2023-WeB/starD-frontend, pull requests merged in 2025-01, with the labels that each got.

#132 fix: 오류 수정
  src/App.js
  src/components/repeat_etc/Header.js
  src/pages/TeamCommunity/StudyPostDetail.js
Labels: :bug: fix, ♻️ refactor

#134 fix 오류 수정
  src/App.js
  src/components/comment/Comment.js
  src/components/comment/CommentForm.js
  src/components/comment/CommentList.js
  src/components/community/CommSearchBar.js
  src/components/community/PostInsert.js
  src/components/community/PostListItem.js
  src/components/notice/NoticeListItem.js
  src/components/qna/QnaListItem.js
  src/components/qna/QnaSearchBar.js
  src/components/repeat_etc/Header.js
  src/components/study/StudyListItem.js
  src/components/teamcommunity/TeamPostListItem.js
  src/pages/TeamCommunity/StudyPostDetail.js
  src/pages/admin/FaqInsert.js
  src/pages/community/Community.js
  src/pages/community/PostDetail.js
  src/pages/mypage/MyWriteComment.js
  src/pages/mypage/MyWritePost.js
  src/pages/qna/Qna.js
  src/pages/qna/QnaInsert.js
  src/pages/studypage/Study.js
  src/pages/studypage/StudyApplyForm.js
  src/pages/studypage/StudyApplyList.js
  src/pages/studypage/StudyDetail.js
  src/pages/studypage/StudyInsert.js
  src/setupProxy.js
Labels: :bug: fix, ♻️ refactor

#137 fix 스터디 상세 조회 페이지 수정
  src/App.js
  src/components/comment/CommentList.js
  src/components/repeat_etc/Header.js
  src/components/study/StudyInfo.js
  src/pages/AuthContext.js
  src/pages/Home.js
  src/pages/studypage/StudyDetail.js
  src/pages/userpage/FindPW.js
  src/pages/userpage/Login.js
  src/pages/userpage/Signup.js
Labels: :bug: fix

#139 fix: 실시간 알림
  src/App.js
  src/components/comment/Comment.js
  src/components/comment/CommentForm.js
  src/pages/Home.js
  src/pages/notification/EventSourceContext.js
  src/pages/notification/Subscribe.js
  src/pages/notification/SubscribeComponent.js
  src/pages/studypage/StudyDetail.js
  src/pages/userpage/Login.js
  src/pages/userpage/Logout.js
Labels: ✨ feature

#145 [#142] alert 창 대신 toast 사용 / css 수정 / 페이징 수정
  package.json
  src/App.css
  src/components/qna/QnaListItem.js
  src/components/repeat_etc/Header.js
  src/pages/Home.js
  src/pages/community/Community.js
  src/pages/community/PostDetail.js
  src/pages/notice/Notice.js
  src/pages/qna/FaqDetail.js
  src/pages/qna/Qna.js
  src/pages/studypage/SearchResult.js
  src/pages/studypage/Study.js
  src/util/likeHandler.js
Labels: bug, enhancement, :bug: fix

#146 feat 팀투두
  package-lock.json
  src/App.js
  src/components/teamtodo/TeamToDoEdit.js
  src/components/teamtodo/TeamToDoInsert.js
  src/components/teamtodo/TeamToDoListItem.js
  src/pages/TeamToDo/TeamToDoList.js
  src/pages/studypage/TeamBlog.js
Labels: ✨ feature

#151 fix 스터디 검색 오류 수정
  src/App.js
  src/SearchBar.js
  src/pages/studypage/Study.js
Labels: bug, :bug: fix

#153 fix: 공지사항, faq, qna, 관리자 페이지 수정
  src/components/community/PostInsert.js
  src/components/repeat_etc/AdminCategory.js
  src/components/repeat_etc/Header.js
  src/pages/admin/Admin.js
  src/pages/admin/FAQManagement.js
  src/pages/admin/FaqInsert.js
  src/pages/admin/MemberManagement.js
  src/pages/admin/NoticeManagement.js
  src/pages/admin/ReportManagement.js
  src/pages/community/PostDetail.js
  src/pages/notice/NoticeDetail.js
  src/pages/notice/NoticeInsert.js
  src/pages/notification/Subscribe.js
  src/pages/qna/Qna.js
  src/pages/qna/QnaInsert.js
Labels: bug, :bug: fix

#155 feat 마이페이지 연동 안된것들
  src/App.css
  src/components/repeat_etc/Category.js
  src/components/study/HomeDashBoard.js
  src/css/community_css/Community.css
  src/css/mypage_css/Mypage_Scrap.css
  src/css/study_css/StudyDashBoard.css
  src/pages/Home.js
  src/pages/community/PostDetail.js
  src/pages/mypage/EditProfile.js
  src/pages/mypage/MyApplyStudy.js
  src/pages/mypage/MyOpenStudy.js
  src/pages/mypage/MyParticipateStudy.js
  src/pages/mypage/MyScrapCommunityPost.js
  src/pages/mypage/MyScrapStudy.js
  src/pages/mypage/MyWriteComment.js
  src/pages/mypage/MyWritePost.js
  src/pages/mypage/Mypage.js
  src/pages/mypage/Profile.js
Labels: ✨ feature

#158 fix: 에러 수정
  src/App.css
  src/components/study/HomeDashBoard.js
  src/css/study_css/StudyDashBoard.css
Labels: bug, :bug: fix

#162 fix: 투두 담당자 여부 확인하기 위해 닉네임 대신 이메일로 검증
  src/components/teamtodo/TeamToDoListItem.js
Labels: bug, :bug: fix

#163 feat 개인 일정
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/datacontext/MyPageContext.js
  src/components/repeat_etc/Loading.js
  src/css/Loading.css
  src/css/mypage_css/Mypage.css
  src/css/schedule_css/ScheduleAdd.css
  src/css/schedule_css/ScheduleCalender.css
  src/css/todo_css/ToDo.css
  src/css/todo_css/ToDoInsert.css
  src/pages/TeamCommunity/TeamCommunity.js
  src/pages/TeamToDo/TeamToDoList.js
  src/pages/mypage/Mypage.js
  src/pages/mypage/Schedule.js
  src/pages/mypage/ToDoList.js
  src/pages/studypage/TeamBlog.js
Labels: :bug: fix, ✨ feature

#167 feat TODO
  src/components/teamtodo/TeamToDoEdit.js
  src/components/teamtodo/TeamToDoListItem.js
  src/components/todo/ToDoListItem.js
  src/css/mypage_css/Mypage.css
  src/css/study_css/ApplyList.css
  src/css/todo_css/ToDoListItem.css
  src/pages/TeamToDo/TeamToDoList.js
  src/pages/mypage/Mypage.js
  src/pages/mypage/Schedule.js
  src/pages/mypage/ToDoList.js
  src/pages/studypage/StudyApplyForm.js
  src/pages/studypage/StudyInsert.js
Labels: bug, ✨ feature

#168 fix: 자잘한 수정
  src/App.js
  src/components/comment/Comment.js
  src/components/comment/CommentList.js
  src/components/image/imageComponent.js
  src/components/info/EditInterest.js
  src/components/repeat_etc/Header.js
  src/components/study/StudyInfo.js
  src/components/study/StudyListItem.js
  src/pages/Home.js
  src/pages/community/PostDetail.js
  src/pages/mypage/AnotherUserProfile.js
  src/pages/mypage/EditProfile.js
  src/pages/mypage/Editinfo.js
  src/pages/mypage/MyParticipateStudy.js
  src/pages/mypage/Profile.js
  src/pages/notice/Notice.js
  src/pages/studypage/StudyApplyList.js
  src/pages/userpage/Login.js
Labels: bug, :bug: fix

#170 feat 투두 체크
  src/components/todo/ToDoListItem.js
  src/css/mypage_css/Mypage.css
  src/css/study_css/TeamBlog.css
  src/css/todo_css/TeamToDoList.css
  src/css/todo_css/ToDoListItem.css
  src/pages/TeamToDo/TeamToDoList.js
  src/pages/mypage/Mypage.js
  src/pages/mypage/ToDoList.js
  src/pages/studypage/TeamBlog.js
Labels: ✨ feature

#173 fix: 프로필 이미지 조회 관련 코드 수정 / 마이페이지 페이징 적용
  src/App.js
  src/components/chat/Chat.js
  src/components/image/imageComponent.js
  src/components/repeat_etc/Category.js
  src/components/schedule/EditSchedule.js
  src/components/study/StudyInfo.js
  src/components/study/StudyListItem.js
  src/components/teamschedules/TeamEditSchedule.js
  src/pages/mypage/MyApplyStudy.js
  src/pages/mypage/MyOpenStudy.js
  src/pages/mypage/MyParticipateStudy.js
  src/pages/mypage/MyScrapCommunityPost.js
  src/pages/mypage/MyScrapStudy.js
  src/pages/qna/QnaDetail.js
  src/pages/studypage/StudyList.js
  src/setupProxy.js
Labels: bug, :bug: fix

#175 feat 알림
  src/App.js
  src/components/repeat_etc/Category.js
  src/components/repeat_etc/Header.js
  src/css/notification_css/Notification.css
  src/pages/mypage/MyApplyStudy.js
  src/pages/mypage/MyOpenStudy.js
  src/pages/mypage/MyParticipateStudy.js
  src/pages/mypage/MyScrapCommunityPost.js
  src/pages/mypage/MyScrapStudy.js
  src/pages/mypage/MyWriteComment.js
  src/pages/mypage/MyWritePost.js
  src/pages/mypage/Mypage.js
  src/pages/notification/Notification.js
Labels: ✨ feature
